name: Code Quality Checks

on:
    pull_request:
        branches: [main]

jobs:
    quality-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run code quality checks
              run: npm run cq
